#!/bin/bash
# Simple script to view and test proofs

echo "=== Viewing Proofs ==="
echo ""
echo "1. Readable text file: results/proofs_readable.txt"
echo "2. Individual Lean files: results/lean_proofs/*.lean"
echo ""
echo "To view a specific proof:"
echo "  cat results/lean_proofs/proof_1_lemma_2.lean"
echo ""
echo "To view all proofs:"
echo "  cat results/proofs_readable.txt | less"
echo ""
echo "=== Testing a proof with Lean REPL ==="
echo ""
echo "The proofs are in Lean 4 format. To verify them manually:"
echo "1. Copy the proof content (theorem + proof)"
echo "2. Paste it into a Lean 4 environment that has miniF2F imports"
echo "3. Or use the verification system that was set up"
echo ""
echo "Note: The REPL expects JSON format, not raw Lean files."
echo "The verification system handles this automatically."
